name: Echo Name on Push
on:
  push:
    branches:
      - master
jobs:
   my-job:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Echo My Name
        run: echo "Vikram Singh"
